spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

app:
  jwt:
    secret: ${JWT_SECRET}
    expirationMs: ${JWT_EXPIRATION_MS:900000}
  bootstrap:
    admin:
      username: demo_admin
      password: demo123
      email: demo_admin@example.com