spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/table-reservations
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: devSecretKeyForJwtSigningMustBeLongEnough123!